feat: :sparkles: adding the navbar to the project
AnaRangel/anarangel.github.io pull request #2
Opened 2024-04-20 13:59 UTC by colmedev

adding the navbar to the project but the burger menú isn't work and the navbar in desktop still fixed 

![image](https://github.com/AnaRangel/anarangel.github.io/assets/161905693/971a2b9d-99e7-40b9-8305-c0db7beaf724)

![image](https://github.com/AnaRangel/anarangel.github.io/assets/161905693/5a925143-0840-4bf3-8358-4c0677f09787)

2024-04-23 14:34 UTC, Zyruks requested changes
Pocas cositas que arreglar, buen PR.

KEEP GOING!

2024-04-23 14:34 UTC, Zyruks commented on src/components/Navbar/Navbar.astro
> +---
Si no tiene Js puedes borrarlo.
```suggestion
```

2024-04-23 14:34 UTC, Zyruks commented on src/components/Navbar/Navbar.astro
> +      d="M6.52155 8.91282C6.38265 8.79585 6.26568 8.65695 6.19258 8.49611C6.11216 8.19638 6.14871 7.90395 6.24375 7.61153C6.40458 7.14365 6.67508 6.73425 6.93095 6.31023C7.20876 5.85697 7.54504 5.454
Agregar TODO: de mover esto a un componente

2024-04-23 14:34 UTC, Zyruks commented on src/components/Navbar/Navbar.astro
> +        <!-- Here it goes the toggle button for the lang -->
```suggestion
        <!-- TODO: Here it goes the toggle button for the lang -->
```

2024-04-23 14:34 UTC, Zyruks commented on src/components/Navbar/Navbar.astro
> +      <li class="listItem">
```suggestion
      <li class="list-item">
```

Intentar mantener las classes en lower case

2024-04-23 14:34 UTC, Zyruks commented on src/components/Navbar/Navbar.astro
> +  @media (width >= 50rem) {
Fuera buena tener media queries estandarizada, así luego no tener problemas con diferentes medias queries en toda la página.

2024-04-23 14:34 UTC, Zyruks commented on src/pages/index.astro
> +    <Navbar />
```suggestion
  <Navbar />
       <main>
  
```

En semantic el main header va fuera de main 

Es decir seria algo tal que 

```html
<header />
<main />
<footer />
```

2024-04-30 13:24 UTC, colmedev commented on src/components/Navbar/Navbar.astro
> +---
Done!!

2024-04-30 13:24 UTC, colmedev commented on src/components/Navbar/Navbar.astro
> +      d="M6.52155 8.91282C6.38265 8.79585 6.26568 8.65695 6.19258 8.49611C6.11216 8.19638 6.14871 7.90395 6.24375 7.61153C6.40458 7.14365 6.67508 6.73425 6.93095 6.31023C7.20876 5.85697 7.54504 5.454
Done

2024-04-30 13:25 UTC, colmedev commented on src/components/Navbar/Navbar.astro
> +        <!-- Here it goes the toggle button for the lang -->
Done!

2024-04-30 13:25 UTC, colmedev commented on src/pages/index.astro
> +    <Navbar />
Done

2024-04-30 13:29 UTC, colmedev commented on src/components/Navbar/Navbar.astro
> +      <li class="listItem">
Done!

2024-05-25 15:23 UTC, merged