feat: add gradient background by sections
AnaRangel/anarangel.github.io pull request #22
Opened 2024-05-25 19:03 UTC by Facundodandrea

Added component for background gradient that changes color depending on the section of the page you are on

PAGE:

![image](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/bc125833-be06-43ba-ad42-cd95c0e4b4bf)

FIGMA:

![image](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/e770ff44-efc4-475b-bf06-8af2147cd990)

2024-05-27 23:05 UTC, Zyruks requested changes
Aparte de esos cambios agregaría en interface un class o style por si quieres pasar custom class o estilos desde el componente.

Y Veo que tienes el Gradient por encima del texto tocaría arreglar el z-index.

Luego veo que está bastante bien el PR.
Unos cuantos cambios y está aprobado ;) 

![BbcanBbcan3GIF](https://github.com/AnaRangel/anarangel.github.io/assets/14036522/c6cb1ee2-fd38-490f-a968-91ee218c0626)

2024-05-27 23:05 UTC, Zyruks commented on src/components/GradientBackground/GradientBackground.astro
> +type GradientSection = 'home' | 'about' | 'ripley' | 'latam' | 'cencosud';
```suggestion
export enum GradientColor {
  blue = 'blue',
  purple = 'purple',
  darkPurple = 'darkPurple',
  darkBlue = 'darkBlue',
  cyan = 'cyan',
}
```


Cambiaria el type por un enum y en vez de darle colores por section lo dejaría más abstracto, usando como nombre el color.

2024-05-27 23:05 UTC, Zyruks commented on src/components/GradientBackground/GradientBackground.astro
> +};
```suggestion
const gradients: Record<GradientColor, string> = {
  [GradientColor.blue]:
    'radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(46, 88, 255, 0.34) 0%, rgba(0, 0, 0, 0.00) 100%)',
  [GradientColor.purple]:
    'radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(148, 82, 255, 0.40) 0%, rgba(0, 0, 0, 0.00) 100%)',
  [GradientColor.darkPurple]:
    'radial-gradient(48.42% 48.42% at 49.41% 51.58%, #1E0D4F 0%, rgba(0, 0, 0, 0.00) 100%)',
  [GradientColor.darkBlue]:
    'radial-gradient(48.42% 48.42% at 49.41% 51.58%, #061962 0%, rgba(0, 0, 0, 0.00) 100%)',
  [GradientColor.cyan]:
    'radial-gradient(35.82% 35.18% at 50.01% 50%, rgba(48, 183, 202, 0.30) 0%, rgba(33, 212, 155, 0.00) 100%)',
};
```

Si haces el cambio a enum quedaría tal que para poder usarlo.

2024-05-27 23:05 UTC, Zyruks commented on src/pages/index.astro
> +    <GradientBackground section="home" />
```suggestion
     <GradientBackground section={GradientColor.darkPurple} />
```

Y como ahora estamos usando el enum quedaría mejor typado y fácil de usar.

2024-05-28 00:08 UTC, Facundodandrea commented
![image](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/f464398a-24b4-47ff-87ca-669eb36486ef)
Listos los cambios en el componente, ahora se puede pasar custom class y se modifico los estilos del hero ya que al colocar un z-index en los estilos del componente background este desaparecía

2024-05-28 15:31 UTC, Zyruks commented
Listo reviso.

2024-05-28 15:33 UTC, Zyruks requested changes
Listo lo veo todo bien con relación al código.

Veo que tienes conflictos con el merge, si necesitas ayuda para solucionar los conflictos me puedes decir.

2024-05-28 15:33 UTC, Zyruks commented on src/components/GradientBackground/GradientBackground.astro
> +  section: GradientColor;
```suggestion
  color: GradientColor;
```
Aquí pasaría a ser color, ya que no está ligado a la sección

2024-05-28 16:00 UTC, Facundodandrea commented
Listo los últimos cambios marcados, solo tengo un conflicto que no se como resolverlo
![image](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/7a1a4355-af1c-44e4-b016-88ec4b411d7d)

2024-05-31 04:59 UTC, Zyruks requested changes

2024-05-31 04:59 UTC, Zyruks commented on pnpm-lock.yaml
Tenemos que ver porque te modifica el pnpm-lock, que no debería, ya que no añades dependencias.

Que versión de `pnpm` tienes usa: `pnpm --version`

2024-06-01 13:25 UTC, merged