Feature/carrusel de testimonios
AnaRangel/anarangel.github.io pull request #38
Opened 2024-05-28 00:23 UTC by luis-codex

#30 

https://github.com/AnaRangel/anarangel.github.io/assets/101147375/120acf7e-b809-49be-800b-296a0637771d

2024-05-31 05:07 UTC, Zyruks commented on src/pages/about-me/_Sections/Testimonials/Testimonials.astro
> +  }
Agregaría un pequeño scale `1.1` o `1.2` a la card cuando se hace el hover.

2024-05-31 05:08 UTC, Zyruks requested changes
![image](https://github.com/AnaRangel/anarangel.github.io/assets/14036522/110fb5f2-1998-4815-838a-1cec66d6a57f)

En mobile tienes un pequeño overlay, luego de eso te puedo mergear :3

2024-05-31 14:01 UTC, luis-codex commented on src/pages/about-me/_Sections/Testimonials/Testimonials.astro
> +  }
Si, Añadire un scale 1.1

2024-05-31 14:19 UTC, luis-codex commented
Hola, Listo

[Coding 2024-05-31 09-12-07.webm](https://github.com/AnaRangel/anarangel.github.io/assets/101147375/761972d4-e43f-433c-828e-1c860485fafc)

2024-06-01 13:26 UTC, Zyruks approved these changes
![ChopApproveCopApproveGIF](https://github.com/AnaRangel/anarangel.github.io/assets/14036522/0a5f177b-6ef6-42cd-aaed-290b9cb043af)

2024-06-01 13:27 UTC, merged