feat: add-footer-component
AnaRangel/anarangel.github.io pull request #4
Opened 2024-04-28 20:16 UTC by SebastianMDB

Add footer component 
![image](https://github.com/AnaRangel/anarangel.github.io/assets/94372671/37cc0697-1ad1-42e0-a370-a0477f91da50)

2024-04-28 23:37 UTC, Zyruks requested changes
Pues lo veo muy bien, si puedes arreglar el problema del `package-lock`  puedes considerarlo approved.

Y las cositas que deje para cambiar son tonterías que se pueden cambiar en cualquier momento.

Gracias por la contribución :3

2024-04-28 23:37 UTC, Zyruks commented on package-lock.json
Estamos usando `pnpm`, y usaste `npm` por eso te genero el `package-lock.json` intenta sacar el `package-lock` por favor que son 13,213 líneas nuevas lol.

2024-04-28 23:37 UTC, Zyruks commented on src/components/Footer.astro
> +    <div class="column1">
```suggestion
    <div class="column-1">
```

2024-04-28 23:37 UTC, Zyruks commented on src/components/Footer.astro
> +    <div class="column2">
```suggestion
    <div class="column-2">
```

No me termina de convencer el nombre, pero eso lo podemos arreglar luego.

2024-04-28 23:37 UTC, Zyruks commented on src/components/Footer.astro
> +---
Agregar un TODO: para hacer un componente que maneje todos esos svg
Parecido al Icon pero más genérico

2024-04-29 00:06 UTC, AnaRangel commented
@SebastianMDB muchas gracias por el PR 🌟 aprecio mucho la contribución al proyecto :) corrige los detalles que te comento zyruks y con mucho gusto los pasamos a main

2024-04-29 18:19 UTC, SebastianMDB commented on src/components/Footer.astro
> +    <div class="column2">
lo dejé asi como placeholder hasta estandarizar las cosas

2024-04-30 12:45 UTC, Zyruks approved these changes
![ChopApproveCopApproveGIF](https://github.com/AnaRangel/anarangel.github.io/assets/14036522/e819d3b3-ead4-447d-9348-6c6334b6c5ac)

2024-04-30 12:45 UTC, merged