feature/contactme component
AnaRangel/anarangel.github.io pull request #45
Opened 2024-05-29 14:45 UTC by luis-codex

### Desktop

![image](https://github.com/AnaRangel/anarangel.github.io/assets/101147375/889880a9-81a7-46bd-ab79-45e50885e2fe)

### Mobile

![image](https://github.com/AnaRangel/anarangel.github.io/assets/101147375/4d4a1789-4437-46c5-8d66-080ee1b57e37)

![image](https://github.com/AnaRangel/anarangel.github.io/assets/101147375/bb2d9d45-a4b9-4596-8306-8c596c416818)

2024-05-31 04:45 UTC, Zyruks requested changes
Buen PR.

2024-05-31 04:45 UTC, Zyruks commented on src/pages/_Sections/Contact/Contact.astro
> +---
```suggestion
```

Se puede eliminar si no tiene nada dentro

2024-05-31 04:45 UTC, Zyruks commented on src/pages/_Sections/Contact/Contact.astro
> +      <span class="contact__button--cv__text">Descargar CV</span>
Puedes usar el componente Button, mira más arriba el ejemplo del Hero

2024-05-31 14:22 UTC, luis-codex commented on src/pages/_Sections/Contact/Contact.astro
> +---
si

2024-05-31 14:24 UTC, luis-codex commented on src/pages/_Sections/Contact/Contact.astro
> +      <span class="contact__button--cv__text">Descargar CV</span>
si

2024-05-31 14:27 UTC, luis-codex commented on src/pages/_Sections/Contact/Contact.astro
> +      <span class="contact__button--cv__text">Descargar CV</span>
![alt text](image.png)

2024-06-01 13:31 UTC, Zyruks approved these changes
![ChopApproveCopApproveGIF](https://github.com/AnaRangel/anarangel.github.io/assets/14036522/1a397d18-5ce2-41e9-9821-21746300409f)

2024-06-01 13:32 UTC, merged