Feature/contributors
AnaRangel/anarangel.github.io pull request #47
Opened 2024-05-29 17:28 UTC by Facundodandrea

### Sección  de contribuciones #20 

- [ ] Llamado de la API de GitHub para los desarrolladores
- [ ] Archivo JSON para los diseñadores 
- [ ] Responsive

https://github.com/AnaRangel/anarangel.github.io/assets/71223579/2c3ce662-7886-4bdf-864a-e368794a919b

Mobile: 

![Screenshot_1](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/8d39512f-0e12-45fd-83b5-6db3e681f829)

2024-05-31 04:55 UTC, Zyruks requested changes
Toca separar eso de los gradients que ya lo tienes en un PR

Aparte no se porque el pnpm-lock siempre se modifica.

2024-05-31 04:55 UTC, Zyruks commented on src/pages/_Sections/Contributors/Contributors.astro
> +<section class="contribuciones">
```suggestion
<section class="contributors">
```

Vamos a mantener las clases en ingles :3

2024-05-31 04:55 UTC, Zyruks commented on src/pages/_Sections/Contributors/Contributors.astro
> +  <span class="contribuciones-subtitle">Desarrollo</span>
Spanglish

2024-05-31 13:12 UTC, Facundodandrea commented on src/pages/_Sections/Contributors/Contributors.astro
> +<section class="contribuciones">
Es la 9.1.2

2024-05-31 14:13 UTC, felixicaza commented
> Toca separar eso de los gradients que ya lo tienes en un PR
> 
> Aparte no se porque el pnpm-lock siempre se modifica.
> 
> Mira que versión de pnpm estás usando y me dejas saber por acá.

Hola @Zyruks, lo del `pnpm.lock` crees que sería buena idea añadirlo al `.gitignore`? Para evitar que se haga commit y genere "ruido" en los PR, además que supongo que cada quién tendrá una versión distinta PNPM, por lo que el archivo se podría estar modificando todo el tiempo.

2024-06-01 13:11 UTC, Zyruks commented
> > Toca separar eso de los gradients que ya lo tienes en un PR
> > Aparte no se porque el pnpm-lock siempre se modifica.
> > Mira que versión de pnpm estás usando y me dejas saber por acá.
> 
> Hola @Zyruks, lo del `pnpm.lock` crees que sería buena idea añadirlo al `.gitignore`? Para evitar que se haga commit y genere "ruido" en los PR, además que supongo que cada quién tendrá una versión distinta PNPM, por lo que el archivo se podría estar modificando todo el tiempo.



El pnpm-lock es necesario para hacer build en otros environments así que debemos subirlos si no se romperían cosas como el deploy en github pages.

Pero tranqui le resuelvo ;)

2024-06-01 22:43 UTC, Zyruks commented
Este PR esta duplicado, estaba el contributor en el bento tambien.

2024-06-01 22:43 UTC, closed without merging